### ISSUE TITLE
Left or right join on more than one column?

### ISSUE THREAD

**Issue by PAX523** [strangecharm2/strangecharm#2]
For performing an inner join, there's this method:

```
DataFrame join(DataFrame df, String[] leftColumnNames, String[] rightColumnNames);
```

And for left/ right join we have:

```
DataFrame joinManyToOne(DataFrame df, String leftColumnName);
DataFrame joinOneToMany(DataFrame df, String rightColumnName);
DataFrame joinLeftOneToMany(DataFrame df, String rightColumnName);
```

But those methods only allow specifying one join column. Is there a way to perform a left/right join on more than one column?

**Comment by biteytech** [comment]
I could add method:
```
DataFrame joinLeft(DataFrame df, String[] leftColumnNames, String[] rightColumnNames);
```
which would work like the inner join variant, but also append any rows from the left DataFrame that don't match at the end of the resulting DataFrame.

Would that work for your use case?

**Comment by biteytech** [comment]
I've gone ahead and added `joinLeft` in `1.2.11`.

**Comment by PAX523** [comment]
Hallo Lior!

That's great! Thank you very much for your quick response! You saved my day, that helps me a lot!

And for a right join, I can simply swap the two data frames.

Have a great day! Cheers!
